.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayOperationsWithTemplate - Debug ]----------"
	@cd "ArrayOperationsWithTemplate" && "$(MAKE)" -f  "ArrayOperationsWithTemplate.mk"
clean:
	@echo "----------Cleaning project:[ ArrayOperationsWithTemplate - Debug ]----------"
	@cd "ArrayOperationsWithTemplate" && "$(MAKE)" -f  "ArrayOperationsWithTemplate.mk" clean
