.PHONY: clean All

All:
	@echo "----------Building project:[ demo - Debug ]----------"
	@cd "demo" && "$(MAKE)" -f  "demo.mk"
clean:
	@echo "----------Cleaning project:[ demo - Debug ]----------"
	@cd "demo" && "$(MAKE)" -f  "demo.mk" clean
