.PHONY: clean All

All:
	@echo "----------Building project:[ DuplicationDeletion - Debug ]----------"
	@cd "DuplicationDeletion" && "$(MAKE)" -f  "DuplicationDeletion.mk"
clean:
	@echo "----------Cleaning project:[ DuplicationDeletion - Debug ]----------"
	@cd "DuplicationDeletion" && "$(MAKE)" -f  "DuplicationDeletion.mk" clean
