.PHONY: clean All

All:
	@echo "----------Building project:[ AddDigitsNumber_Type2 - Debug ]----------"
	@cd "AddDigitsNumber_Type2" && "$(MAKE)" -f  "AddDigitsNumber_Type2.mk"
clean:
	@echo "----------Cleaning project:[ AddDigitsNumber_Type2 - Debug ]----------"
	@cd "AddDigitsNumber_Type2" && "$(MAKE)" -f  "AddDigitsNumber_Type2.mk" clean
