.PHONY: clean All

All:
	@echo "----------Building project:[ AddDigitsNumber - Debug ]----------"
	@cd "AddDigitsNumber" && "$(MAKE)" -f  "AddDigitsNumber.mk"
clean:
	@echo "----------Cleaning project:[ AddDigitsNumber - Debug ]----------"
	@cd "AddDigitsNumber" && "$(MAKE)" -f  "AddDigitsNumber.mk" clean
