.PHONY: clean All

All:
	@echo "----------Building project:[ EvaluatePostfix - Debug ]----------"
	@cd "EvaluatePostfix" && "$(MAKE)" -f  "EvaluatePostfix.mk"
clean:
	@echo "----------Cleaning project:[ EvaluatePostfix - Debug ]----------"
	@cd "EvaluatePostfix" && "$(MAKE)" -f  "EvaluatePostfix.mk" clean
